// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB6iQlTSW5kY24p8BkiypaSdJDdsEB6wDE",
      authDomain: "authelp-59c85.firebaseapp.com",
      databaseURL: "https://authelp-59c85-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "authelp-59c85",
      storageBucket: "authelp-59c85.firebasestorage.app",
      messagingSenderId: "79609830834",
      appId: "1:79609830834:web:aa61f0f10f2a42eb9a18ab",
      measurementId: "G-2HL5Z68SGP"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuUhBx6H247NZJ2sa9Klc_vS70ynZzjfM',
    appId: '1:79609830834:android:72632c6f2bdd836d9a18ab',
    messagingSenderId: '79609830834',
    projectId: 'authelp-59c85',
    storageBucket: 'authelp-59c85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_7dryK5GvbcPesZuDhbuMlf7Cbdt8Aq0',
    appId: '1:79609830834:ios:76c85461263fdc409a18ab',
    messagingSenderId: '79609830834',
    projectId: 'authelp-59c85',
    storageBucket: 'authelp-59c85.firebasestorage.app',
    iosBundleId: 'com.example.help',
  );
}
